// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../../../main.h"
#include "../../../plugins/BLEScalePlugin.h"
#include "ui.h"
#include <Arduino.h>

// Flag to track if volumetric hold was triggered
static bool volumetricHoldTriggered = false;

void onBrewCancel(lv_event_t *e) {
    controller.postCommand(CtrlCmd::DEACTIVATE);
    controller.postCommand(CtrlCmd::CLEAR);
}

void onBrewStart(lv_event_t *e) { controller.postCommand(CtrlCmd::ACTIVATE); }

void onBrewTempLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.postCommand(CtrlCmd::LOWER_TEMP);
}

void onBrewTempRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.postCommand(CtrlCmd::RAISE_TEMP);
}

void onBrewTimeLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.lowerBrewTarget();
}

void onBrewTimeRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.raiseBrewTarget();
}

void onSteamTempLower(lv_event_t *e) { controller.postCommand(CtrlCmd::LOWER_TEMP); }

void onSteamTempRaise(lv_event_t *e) { controller.postCommand(CtrlCmd::RAISE_TEMP); }

void onBrewScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.postCommand(CtrlCmd::DEACTIVATE);
    controller.postCommand(CtrlCmd::SET_MODE, MODE_BREW);
}

void onWaterScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.postCommand(CtrlCmd::DEACTIVATE);
    controller.postCommand(CtrlCmd::SET_MODE, MODE_WATER);
}

void onSteamScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.postCommand(CtrlCmd::DEACTIVATE);
    controller.postCommand(CtrlCmd::SET_MODE, MODE_STEAM);
}

void onWakeup(lv_event_t *e) {
    if (controller.isUpdating() || controller.isErrorState() || controller.isAutotuning() ||
        !controller.getClientController()->isConnected()) {
        return;
    }
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.postCommand(CtrlCmd::DEACTIVATE);
    controller.postCommand(CtrlCmd::SET_MODE, MODE_BREW);
}

void onLoadStarted(lv_event_t *e) {}

void onStandby(lv_event_t *e) { controller.postCommand(CtrlCmd::ACTIVATE_STANDBY); }

void onGrindToggle(lv_event_t *e) {
    controller.postCommand(controller.isGrindActive() ? CtrlCmd::DEACTIVATE_GRIND : CtrlCmd::ACTIVATE_GRIND);
}

void onGrindTimeLower(lv_event_t *e) { controller.postCommand(CtrlCmd::LOWER_GRIND_TARGET); }

void onGrindTimeRaise(lv_event_t *e) { controller.postCommand(CtrlCmd::RAISE_GRIND_TARGET); }

void onMenuClick(lv_event_t *e) {
    controller.postCommand(CtrlCmd::DEACTIVATE);
    controller.postCommand(CtrlCmd::SET_MODE, MODE_BREW);
    controller.getUI()->changeScreen(&ui_MenuScreen, &ui_MenuScreen_screen_init);
}

void onGrindScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_screen_init);
    controller.postCommand(CtrlCmd::SET_MODE, MODE_GRIND);
}

void onVolumetricClick(lv_event_t *e) {
    if (volumetricHoldTriggered) {
        volumetricHoldTriggered = false;
        return;
    }
    auto &settings = controller.getSettings();
    if (controller.getMode() == MODE_GRIND) {
        // Grind-by-weight is BLE-only. This toggles weight vs timed grind; the
        // controller will use timed grind if no Bluetooth scale is connected.
        settings.setVolumetricTarget(!settings.isVolumetricTarget());
    } else {
        // Brew role: BLE (1) → HW (2, UART only) → Predictive (3) → OFF (4) → BLE.
        int src = settings.getScaleSource();
#if defined(GAGGIMATE_UART_COMMS) && !defined(GAGGIMATE_DISABLE_HARDWARE_SCALE)
        int next = (src >= 1 && src <= 3) ? src + 1 : 1;
#else
        int next = (src == 1) ? 3 : (src == 3) ? 4 : 1;
#endif
        settings.setScaleSource(next);
    }
}

void onPreviousProfile(lv_event_t *e) { controller.getUI()->onPreviousProfile(); }

void onNextProfile(lv_event_t *e) { controller.getUI()->onNextProfile(); }

void onProfileLoad(lv_event_t *e) { controller.getUI()->onProfileSelect(); }

void onProfileSelect(lv_event_t *e) { controller.getUI()->onProfileSwitch(); }

void onFlush(lv_event_t *e) { controller.onFlush(); }

void onSimpleProcessToggle(lv_event_t *e) {
    if (controller.getMode() != MODE_STEAM) {
        controller.postCommand(controller.isActive() ? CtrlCmd::DEACTIVATE : CtrlCmd::ACTIVATE);
    }
}

void onProfileScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_ProfileScreen_previousProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_nextProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_chooseButton, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_ImgButton1, 20);
}

void onMenuScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_MenuScreen_btnBrew, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_btnSteam, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_waterBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_grindBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_standbyButton, 20);
}

void onBrewScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_BrewScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_profileSelectBtn, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_ImgButton5, 20);
    lv_obj_set_ext_click_area(ui_BrewScreen_upDurationButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_downDurationButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_upTempButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_downTempButton, 15);
}

void onSimpleProcessScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_downTempButton, 40);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_upTempButton, 40);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_goButton, 25);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_ImgButton6, 20);
}

void onStatusScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_StatusScreen_pauseButton, 25);
    lv_obj_set_ext_click_area(ui_StatusScreen_ImgButton8, 20);
}

void onGrindScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_GrindScreen_upDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_GrindScreen_ImgButton2, 20);
}

void onProfileSettings(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Settings); }

void onProfileSave(lv_event_t *e) {
    controller.onProfileSave();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onProfileAccept(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew); }

void onProfileSaveAsNew(lv_event_t *e) {
    controller.onProfileSaveAsNew();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onVolumetricHold(lv_event_t *e) {
    // Set flag to prevent click from firing when button is released
    volumetricHoldTriggered = true;

    controller.getClientController()->tare();
    BLEScales.tare();
}

void onVolumetricDelete(lv_event_t *e) { controller.getUI()->onVolumetricDelete(); }
